# Generated by Django 5.2.5 on 2025-08-25 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.IntegerField(choices=[(0, 'Strength Chest'), (1, 'Strength Back'), (2, 'Strength Arms'), (3, 'Strength Abdominals'), (4, 'Strength Legs'), (5, 'Strength Shoulders'), (6, 'Aerobic'), (7, 'Flexibility')])),
            ],
        ),
        migrations.CreateModel(
            name='OrderedExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FitnessScheduler.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ordered_exercises', models.ManyToManyField(to='FitnessScheduler.orderedexercises')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduledtime', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FitnessScheduler.exerciseplan')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('missed', models.BooleanField()),
                ('scheduled_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FitnessScheduler.scheduledexercise')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_binding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('records', models.ManyToManyField(to='FitnessScheduler.record')),
                ('saved_plans', models.ManyToManyField(to='FitnessScheduler.exerciseplan')),
                ('scheduled_plans', models.ManyToManyField(to='FitnessScheduler.scheduledexercise')),
            ],
        ),
    ]
